Update telco_news_forward.yml

diff --git a/.github/workflows/telco_news_forward.yml b/.github/workflows/telco_news_forward.yml
--- a/.github/workflows/telco_news_forward.yml
+++ b/.github/workflows/telco_news_forward.yml
@@ -21,11 +21,30 @@ jobs:
     - name: Install Python dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install python-telegram-bot
+        pip install python-telegram-bot --upgrade
+
+    - name: Check environment variables
+      run: |
+        if [ -z "${{ secrets.TELEGRAM_TOKEN }}" ]; then
+          echo "Error: TELEGRAM_TOKEN is not set"
+          exit 1
+        fi
+        if [ -z "${{ secrets.TELCO_NEWS_RECEIVE }}" ]; then
+          echo "Error: TELCO_NEWS_RECEIVE is not set"
+          exit 1
+        fi
+        if [ -z "${{ secrets.TELCO_NEWS_BROADCAST_1 }}" ]; then
+          echo "Error: TELCO_NEWS_BROADCAST_1 is not set"
+          exit 1
+        fi
+        if [ -z "${{ secrets.TELCO_NEWS_BROADCAST_2 }}" ]; then
+          echo "Error: TELCO_NEWS_BROADCAST_2 is not set"
+          exit 1
+        fi
 
     - name: Run forwarder script
       env:
-        TELEGRAM_TOKEN: ${{ secrets.TELCO_NEWS_TOKEN }}
+        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
         TELCO_NEWS_RECEIVE: ${{ secrets.TELCO_NEWS_RECEIVE }}
         TELCO_NEWS_BROADCAST_1: ${{ secrets.TELCO_NEWS_BROADCAST_1 }}
         TELCO_NEWS_BROADCAST_2: ${{ secrets.TELCO_NEWS_BROADCAST_2 }}
